services:
  postgres:
    container_name: jwt-auth
    image: postgres
    environment:
      POSTGRES_USER: jwt-auth
      POSTGRES_PASSWORD: jwt-auth
      POSTGRES_DB: jwt-auth
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres: