version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: jwt-auth
      POSTGRES_PASSWORD: jwt-auth
      POSTGRES_DB: jwt-auth
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - db
    restart: unless-stopped
  springservice:
    container_name: spring3
    image: spring3-example:0.0.2-SNAPSHOT
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - db

networks:
  db:
    driver: bridge

volumes:
  postgres: